install.packages("expsmooth")
library(expsmooth)
data(visitors)
plot(visitors)
head(visitors)
tail(visitors)
period<-1:length(visitors)
raw<-data.frame(cbind(visitors,period))
timetrend<-lm(visitors~period+I(log(period)),data=raw)
raw$timetrend<-predict(timetrend,raw)
raw$withouttimetrend<-raw$visitors-raw$timetrend
plot(raw$withouttimetrend,type='o')
seasonsmatrix = t(matrix(data = raw$withouttimetrend, nrow = 12))
seasons = colMeans(seasonsmatrix, na.rm = T)
raw$seasons<-c(rep(seasons,20))
raw$error<-raw$visitors-raw$timetrend-raw$seasons
plot(raw$error,type='o')
par(mfrow=c(3,1))
plot(raw$timetrend,type='o')
plot(raw$seasons,type='o')
plot(raw$error,type='o')
